#!/usr/bin/env bash
# .notes/install.sh
#
# One-shot installer. Run from the repo root:
#
#   bash .notes/install.sh
#
# Installs:
#   - .git/hooks/pre-commit       (same-commit rule)
#   - .git/hooks/commit-msg       (commit anchor rule)
#   - .github/workflows/notes-check.yml  (CI fallback for un-hooked clients)
#
# Idempotent — safe to re-run after pulling updates.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$REPO_ROOT" ]]; then
  echo "✗ Not inside a git repo. Run \`git init\` first."
  exit 1
fi

NOTES_DIR="$REPO_ROOT/.notes"
if [[ ! -d "$NOTES_DIR" ]]; then
  echo "✗ $NOTES_DIR not found. Copy the .notes/ directory in first."
  exit 1
fi

echo "Installing Repo Handoff Notes v2 enforcement..."

# 1. Make all .notes scripts executable
chmod +x "$NOTES_DIR"/hooks/* "$NOTES_DIR"/scripts/*.sh 2>/dev/null || true

# 2. Wire git hooks
HOOK_DIR="$REPO_ROOT/.git/hooks"
mkdir -p "$HOOK_DIR"

for hook in pre-commit commit-msg; do
  TARGET="$HOOK_DIR/$hook"
  if [[ -f "$TARGET" ]] && ! grep -q "notes/hooks/$hook" "$TARGET" 2>/dev/null; then
    # Existing hook from another tool — chain instead of clobber
    BACKUP="$TARGET.pre-notes-backup"
    if [[ ! -f "$BACKUP" ]]; then
      cp "$TARGET" "$BACKUP"
      echo "  • Backed up existing $hook to $hook.pre-notes-backup"
    fi
  fi
  cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# Auto-generated by .notes/install.sh — do not edit directly.
# Chains to any pre-existing hook (saved as $hook.pre-notes-backup).
set -e
REPO_ROOT="\$(git rev-parse --show-toplevel)"
if [[ -f "\$REPO_ROOT/.git/hooks/$hook.pre-notes-backup" ]]; then
  bash "\$REPO_ROOT/.git/hooks/$hook.pre-notes-backup" "\$@" || exit \$?
fi
exec bash "\$REPO_ROOT/.notes/hooks/$hook" "\$@"
EOF
  chmod +x "$TARGET"
  echo "  ✓ Installed $hook hook"
done

# 3. Wire GitHub Actions workflow
WORKFLOW_DIR="$REPO_ROOT/.github/workflows"
mkdir -p "$WORKFLOW_DIR"
cp "$NOTES_DIR/workflows/notes-check.yml" "$WORKFLOW_DIR/notes-check.yml"
echo "  ✓ Installed CI workflow at .github/workflows/notes-check.yml"

# 4. Seed notes files if missing
# shellcheck disable=SC1091
source "$NOTES_DIR/config.sh"
for f in "$NOTES_AI_FILE" "$NOTES_BACKEND_FILE"; do
  if [[ ! -f "$REPO_ROOT/$f" ]]; then
    case "$f" in
      "$NOTES_AI_FILE")
        cat > "$REPO_ROOT/$f" <<EOF
# $f

<!-- Convention: Repo Handoff Notes v2 (https://github.com/heatonb1/repo-handoff-notes) -->

Running log from local dev → Lovable for **frontend** changes.
Backend changes go in \`$NOTES_BACKEND_FILE\`. If a change spans both,
log it in the more-relevant file and post a brief cross-ref stub in
the other.

## How to use

- **\`[STATUS: NEW]\`** — needs the other party's attention
- **\`[STATUS: PROCESSED]\`** — acted on, with one-line result + commit short-hash
- **\`[STATUS: BLOCKED: <reason>]\`** — read but can't act; routes back

Newest entries on top. Never edit \`[PROCESSED]\` entries.
Never put secrets, tokens, or keys here — reference secret names only.

_Add new entries above this line._
EOF
        echo "  ✓ Seeded $f"
        ;;
      "$NOTES_BACKEND_FILE")
        cat > "$REPO_ROOT/$f" <<EOF
# $f

<!-- Convention: Repo Handoff Notes v2 (https://github.com/heatonb1/repo-handoff-notes) -->

Running log from local dev → Lovable for **backend** changes
(migrations, edge functions, RLS, secrets, auth, storage, cron).
Frontend changes go in \`$NOTES_AI_FILE\`. If a change spans both,
log it in the more-relevant file and post a brief cross-ref stub in
the other.

## How to use

- **\`[STATUS: NEW]\`** — needs the other party's attention
- **\`[STATUS: PROCESSED]\`** — acted on, with one-line result + commit short-hash
- **\`[STATUS: BLOCKED: <reason>]\`** — read but can't act; routes back

Newest entries on top. Never edit \`[PROCESSED]\` entries.
Never put secrets, tokens, or keys here — reference secret names only.

_Add new entries above this line._
EOF
        echo "  ✓ Seeded $f"
        ;;
    esac
  fi
done

# 5. Create a starter .notesrc if missing (user-customizable, gitignored)
if [[ ! -f "$REPO_ROOT/.notesrc" ]]; then
  cat > "$REPO_ROOT/.notesrc" <<'EOF'
# .notesrc — local overrides for the Repo Handoff Notes enforcement.
# Commit-tracked or git-ignored, your choice. Uncomment to override defaults.

# NOTES_MODE=strict                                     # strict | warn | off
# NOTES_FRONTEND_PATHS="src/ public/ index.html"
# NOTES_BACKEND_PATHS="supabase/"
# NOTES_REQUIRE_COMMIT_ANCHOR=1
# NOTES_REJECT_TBD_IN_PROCESSED=1
EOF
  echo "  ✓ Created .notesrc starter (commit or .gitignore as you prefer)"
fi

echo ""
echo "Done. Enforcement is live."
echo ""
echo "Try it:"
echo "  .notes/scripts/new-entry.sh backend \"Test entry\""
echo "  .notes/scripts/list-new.sh"
echo ""
echo "Emergency bypass:  NOTES_SKIP=1 git commit ..."
echo "Disable entirely:  set NOTES_MODE=off in .notesrc"
